include ':bridge'

// Debugging tool
include ':debugger'

// Testing app
include ':test-app'

// Instrumentation
include ':instrumentation:session-recording:frame-capturer',
		':instrumentation:session-recording:interactions',
		':instrumentation:session-recording:wireframe',
		':instrumentation:session-recording:screenshot',
		':instrumentation:session-recording:core'
