blank_issues_enabled: false
contact_links:
  - name: Splunk RUM for Android — Installation & Configuration
    url: https://help.splunk.com/en/splunk-observability-cloud/manage-data/instrument-front-end-applications/instrument-mobile-and-web-applications-for-splunk-rum/instrument-android-applications-for-splunk-rum/splunk-rum-android-agent-version-2.0.0-and-above/install-the-splunk-rum-android-agent
    about: Setup, configuration, and usage documentation for the Agent.
  - name: Splunk RUM for Android — Session Replay
    url: https://help.splunk.com/en/splunk-observability-cloud/monitor-end-user-experience/real-user-monitoring/replay-user-sessions/record-android-sessions
    about: Configure and use Session Replay in Android apps, including recording controls, rendering modes, masking sensitive data, and replay privacy settings.